apiVersion: batch/v1
kind: Job
metadata:
  name: evalai-debug-runner
  namespace: evalai-poc
spec:
  backoffLimit: 0
  # ttlSecondsAfterFinished: 300 
  template:
    spec:
      containers:
      - name: debug-runner
        image: ghcr.io/kmom88/evalaistartertest:latest 
        
        imagePullPolicy: Always
        
        envFrom:
        - secretRef:
            name: evalai-runner-secrets
            
        env:
        - name: SAVE_DIR
          value: "/tmp"
      restartPolicy: Never